#!/bin/bash -e

get_info() {
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                                    INFO                                         ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  if [[ "${DISTRO}" =~ ^(centos|rockylinux)[0-9]$ ]]; then
    INFO_RELEASE="$(cat /etc/redhat-release)"
    PKG_POSTGRES_SERVER_VER=$(rpm -qa postgresql${SHORTVER}-server|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_POSTGRES_DEV_VER=$(rpm -qa postgresql${SHORTVER}-devel|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_FREETDS_VER=$(rpm -qa freetds|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_FREETDS_DEV_VER=$(rpm -qa freetds-devel|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    LLVM_VER=$(rpm -qa "llvm[0-9]?.?[0-9]?"|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    CLANG_VER=$(rpm -qa "(llvm-toolset-[0-9]-clang|clang)"|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
  elif [[ "${DISTRO}" =~ ^(opensuseleap)[0-9]{2}.[0-9]+$ ]]; then
    INFO_RELEASE="$(. /etc/os-release; echo ${VERSION})"
    PKG_POSTGRES_SERVER_VER=$(rpm -qa postgresql${SHORTVER}-server|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_POSTGRES_DEV_VER=$(rpm -qa postgresql${SHORTVER}-devel|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_FREETDS_VER=$(rpm -qa freetds|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    PKG_FREETDS_DEV_VER=$(rpm -qa freetds-devel|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    LLVM_VER=$(rpm -qa "llvm[0-9]?.?[0-9]?"|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
    CLANG_VER=$(rpm -qa "(llvm[0-9]+-libclang[0-9]+)"|rev|cut -d '.' -f2,3-|cut -d '-' -f 1,2|rev)
  elif [[ "${DISTRO}" =~ ^ubuntu[0-9]{2}.[0-9]{2}$ ]]; then
    INFO_RELEASE="$(. /etc/os-release; echo ${VERSION})"
    PKG_POSTGRES_SERVER_VER=$(dpkg -s postgresql-${PG_VER}|grep '^Version:'|cut -d ' ' -f 2)
    PKG_POSTGRES_DEV_VER=$(dpkg -s postgresql-server-dev-${PG_VER}|grep '^Version:'|cut -d ' ' -f 2)
    PKG_FREETDS_VER=$(dpkg -s freetds-common|grep '^Version:'|cut -d ' ' -f 2)
    PKG_FREETDS_DEV_VER=$(dpkg -s freetds-dev|grep '^Version:'|cut -d ' ' -f 2)
    LLVM_VER=$(dpkg-query -f '${Package}#${Version}\n' -W 'llvm-*' 2>/dev/null|grep -P '^llvm-\d+\.\d+#.*'|cut -d'#' -f2)
    CLANG_VER=$(dpkg-query -f '${Package}#${Version}\n' -W 'clang-*' 2>/dev/null|grep -P '^clang-\d+\.\d+#.*'|cut -d'#' -f2)
  fi
  echo "DIST RELEASE: ${INFO_RELEASE}"
  echo "**** PACKAGE VERSIONS ****"
  echo "POSTGRESQL-SERVER: ${PKG_POSTGRES_SERVER_VER}"
  echo "POSTGRESQL-DEV:    ${PKG_POSTGRES_DEV_VER}"
  echo "FREETDS:           ${PKG_FREETDS_VER}"
  echo "FREETDS-DEV:       ${PKG_FREETDS_DEV_VER}"
  if [ ! -z ${LLVM_VER} ]; then
      echo "LLVM:              ${LLVM_VER}"
  fi
  if [ ! -z ${CLANG_VER} ]; then
      echo "CLANG:             ${CLANG_VER}"
  fi
}

mod_build() {
  cd ${TDSDIR}
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                                  BUILDING                                       ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  PATH=${PGBIN_PATH}:${PATH} make USE_PGXS=1
}

mod_install() {
  cd ${TDSDIR}
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                                 INSTALLING                                      ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  sudo PATH=${PGBIN_PATH}:${PATH} make USE_PGXS=1 install
}

pg_start() {
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                       WAITING POSTGRESQL SERVICE START                          ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  if [ -z "${MAXRETRIES}" ]; then
    MAX_RETRIES=40
  fi
  if [ -z "${WAIT_SEC}" ]; then
    WAIT_SEC=5
  fi
  RETRIES=0
  echo "Checking if database engine is started..."
  set +e
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c 'SELECT version();' &> /dev/null
  while [ $? -eq 2 -a ${RETRIES} -lt ${MAX_RETRIES} ]; do
    echo "Database engine is starting up. Waiting ${WAIT_SEC} seconds..."
    sleep ${WAIT_SEC}
    let "RETRIES++"
    ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c 'SELECT version();' &> /dev/null
  done
  set -e
  if [ ${RETRIES} -eq ${MAX_RETRIES} ]; then
    echo "Can't connect to database engine after ${MAX_RETRIES} retries!"
    exit 1
  else
    echo "Database engine is started."
  fi
}

pg_confdb() {
  cd ${TDSDIR}
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                       CONFIGURING DB AND LOADING EXTENSION                      ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c 'SELECT version();'
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c "DROP DATABASE IF EXISTS ${POSTGRESDB};"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c "CREATE DATABASE ${POSTGRESDB};"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c 'CREATE EXTENSION tds_fdw;'
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c '\dx tds_fdw'
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c "DROP USER IF EXISTS ${POSTGRESUSER};"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c "CREATE USER ${POSTGRESUSER} WITH PASSWORD '${POSTGRESPASS}';"
  # Required so the user can read data_directory and log_directory from pg_catalog.pg_settings
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c "ALTER USER ${POSTGRESUSER} WITH SUPERUSER;"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c "GRANT ALL PRIVILEGES ON DATABASE tds_fdw TO ${POSTGRESUSER};"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -d ${POSTGRESDB} -c "GRANT ALL ON FOREIGN DATA WRAPPER tds_fdw TO ${POSTGRESUSER};"
}

mssql_test() {
  cd ${TDSDIR}/tests
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                                RUNNING MSSQL TESTS                              ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  PYTHONUNBUFFERED=True ${PYTHON} ./mssql-tests.py --server ${MSSQLHOST} --port ${MSSQLPORT} --database ${MSSQLDB} --username ${MSSQLUSER} --password ${MSSQLPASS} --schema "${MSSQLSCHEMA}" --azure
}

pg_test() {
  cd ${TDSDIR}/tests
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                              RUNNING POSTGRESQL TESTS                           ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  if [ "${UNATTENDED_DEBUG}" == "TRUE" ]; then
    UNATTENDED_DEBUGGING="--unattended_debugging"
  fi
  POSTGRESHOST='127.0.0.1'
  echo "**** DEBUGGING INFO ****"
  echo "TDS_FDW_MSG_HANDLER:   ${TDS_FDW_MSG_HANDLER}"
  echo "POSTGRES_MIN_MESSAGES: ${POSTGRES_MIN_MESSAGES}"
  echo "UNATTENDED_DEBUG: ${UNATTENDED_DEBUG}"
  echo "*** END OF DEBUGGING INFO ****"
  PYTHONUNBUFFERED=True ${PYTHON} ./postgresql-tests.py --mssql_server ${MSSQLHOST} --mssql_port ${MSSQLPORT} --mssql_database tds_fdw_jenkins --mssql_username ${MSSQLUSER} --mssql_password ${MSSQLPASS} --mssql_schema ${MSSQLSCHEMA} --postgres_server ${POSTGRESHOST} --postgres_port ${POSTGRESPORT} --postgres_database ${POSTGRESDB} --postgres_username ${POSTGRESUSER} --postgres_password ${POSTGRESPASS} --postgres_schema ${POSTGRESSCHEMA} --tds_fdw_msg_handler="${TDS_FDW_MSG_HANDLER}" --postgres_min_messages="${POSTGRES_MIN_MESSAGES}" --azure ${UNATTENDED_DEBUGGING}
}

pg_dropdb() {
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  echo -e "${PURPLEBOLD}                                  DROPPING DB                                    ${COLORCLEAR}"
  echo -e "${PURPLEBOLD}=================================================================================${COLORCLEAR}"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c "DROP DATABASE IF EXISTS ${POSTGRESDB};"
  ${PGBIN_PATH}/psql -p ${POSTGRESPORT} -e -c "DROP USER IF EXISTS ${POSTGRESUSER};"
}
