#!/bin/bash

check_mssql_vars() {
  if [ -z "${MSSQLHOST}" -o \
       -z "${MSSQLPORT}" -o \
       -z "${MSSQLDB}" -o \
       -z "${MSSQLUSER}" -o \
       -z "${MSSQLPASS}" ]; then
    return 1
  else
    return 0
  fi
}

check_postgres_vars() {
  if [ -z "${POSTGRESDB}" -o \
       -z "${POSTGRESUSER}" -o \
       -z "${POSTGRESPASS}" ]; then
    return 1
  else
    return 0
  fi
}

detect_distro() {
  local SUPPORTEDDISTRO=""
  for SUPPORTEDDISTRO in ${SUPPORTEDDISTROS}; do
    if [ "${DISTRO}" == "${SUPPORTEDDISTRO}" ]; then
      echo "${DISTRO}"
      return 0
    fi
  done
  echo ""
  return 1
}

check_pgver() {
  local SUPPORTEDPGVER=""
  for SUPPORTEDPGVER in ${SUPPORTEDPGVERS}; do
    if [ "${PG_VER_FULL}" == "${SUPPORTEDPGVER}" ]; then
      echo "${PG_VER_FULL}"
      return 0
    fi
  done
  echo ""
  return 1
}
